language: crystal

before_install:
  - sudo apt-get update
  - sudo apt-get install -y wget build-essential
  - wget https://github.com/mongodb/mongo-c-driver/releases/download/1.1.0/mongo-c-driver-1.1.0.tar.gz
  - tar -zxvf mongo-c-driver-1.1.0.tar.gz && cd mongo-c-driver-1.1.0/
  - ./configure --prefix=/usr --libdir=/usr/lib64
  - make
  - sudo make install
